#!/usr/bin/env bash


###############################################################
#            A program for boost your linux cpu               #
#            Coded by : Rifai Akbar a.k.a PAIDJEMZ            #
#            Website: https://paidjemz.wordpress.com          #
#            Contact Me: https://t.me/rifai_akm               #
#                                                             #
#                       Made with <3                          #
#                                                             #
###############################################################

# pewarna
cyan='\e[0;36m'
green='\e[0;34m'
okegreen='\033[92m'
lightgreen='\e[1;32m'
white='\e[1;37m'
red='\e[1;31m'
yellow='\e[0;33m'
BlueF='\e[1;34m' #Biru
RESET="\033[00m" #normal
orange='\e[38;5;166m'

# tafsir
cek1="/sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors"
cek2="/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor"

# resize terminal
resize -s 39 70 > /dev/null

function ctrl_c() {
	# tangkap ctrl+c 
	echo -e "\n"
	echo -e $red"---- Interrupted by CTRL+C ----"
	echo "Exiting..." && sleep 1.5
	exit 0
}

function nomer3() {
	clear
	echo -e $white ""
	echo -e $white"	[$okegreen"1"$white]$okegreen Powersave"
	echo -e $white"	[$okegreen"2"$white]$okegreen Performance"
	echo -e $white ""
	echo -e $white"	[$okegreen"3"$white]$okegreen Back to menu"
	echo -e $okegreen" ┌─["$red"Type your choice$okegreen]~:"
	echo -ne $okegreen" └─────► " ;tput sgr0
	read set

	if [ $set == '1' ]; then
		`echo powersave | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor`
		clear && echo -e $okegreen"Set powersave success.."
		sleep 1.5 && clear
		nomer3

	elif [ $set == '2' ]; then
		`echo performance | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor`
		clear && echo -e $okegreen"Set performance success.."
		sleep 1.5 && clear
		nomer3

	elif [ $set == '3' ]; then
		clear && home

	fi
}

function banner() {
	clear && sleep 1.5
	echo -e $red""
	echo "	 									"
	echo "   	                  ..:::::::::..		"
	echo "   	               ..:::aad8888888baa:::..	"
	echo "   	           .::::d:?88888888888?::8b::::.	"
	echo "   	         .:::d8888:?88888888??a888888b:::.	"
	echo "   	       .:::d8888888a8888888aa8888888888b:::.	"
	echo "   	      ::::dP::::::::88888888888::::::::Yb::::	"
	echo "   	     ::::dP:::::::::Y888888888P:::::::::Yb::::	"
	echo "   	    ::::d8:::::::::::Y8888888P:::::::::::8b::::	"
	echo "   	   .::::88::::::::::::Y88888P::::::::::::88::::.	"
	echo "   	   :::::Y8baaaaaaaaaa88P:T:Y88aaaaaaaaaad8P:::::	"
	echo "   	   :::::::Y88888888888P::|::Y88888888888P:::::::	"
	echo "   	   ::::::::::::::::888:::|:::888::::::::::::::::	"
	echo "   	    :::::::::::::::8888888888888b::::::::::::::	"
	echo "   	    :::::::::::::::88888888888888::::::::::::::	"
	echo "   	     :::::::::::::d88888888888888::::::::::::: 	"
	echo "   	      ::::::::::::88::88::88:::88::::::::::::	"
	echo "   	        ::::::::::88::88::88:::88::::::::::	"
	echo "   	          ::::::::88::88::P::::88::::::::	"
	echo "   	            ::::::88::88:::::::88::::::	"
	echo "   	                :::::::::::::::::::	"
	echo "   	                     ::::::::: 	"
	echo ""
	sleep 2
	echo -e $okegreen "		      CPU FREQ TOOLS LINUX 					"
	sleep 1.5
	echo -e $cyan 	  "		   Rifai Akbar a.k.a PAIDJEMZ"
}

function home() {
	# Tangkap sinyal CTRL+C 
	trap ctrl_c INT 

	echo -e $white ""
	echo -e $white"	[$okegreen"01"$white]$okegreen CPU List Available"
	echo -e $white"	[$okegreen"02"$white]$okegreen Check Currently Use Mode"
	echo -e $white"	[$okegreen"03"$white]$okegreen Set CPU Mode"
	echo -e $white"	[$okegreen"04"$white]$okegreen Clear User Cache"
	echo -e $white"	[$okegreen"05"$white]$okegreen Exit"
	echo -e ""
	echo -e $okegreen" ┌─["$red"Choose$okegreen]──[$red~$okegreen]─:"
    echo -ne $okegreen" └─────► " ;tput sgr0
    read clr

    if test $clr == '1'
    	then
    	cat < $cek1
    	sleep 2 && clear
    	home
    
    elif test $clr == '2'
    	then
    	cat < $cek2
    	sleep 2 && clear
    	home

    elif test $clr == '3'
    	then
    	nomer3

    elif test $clr == '4'
    	then
    	`rm -rf ~/.cache/*` #command to delete all user cache file
    	echo -e $okegreen "Clearing User Cache .." 
    	sleep 2.5 && clear
    	home

    elif test $clr == '5'
    	then
    	echo -e $okegreen"Exiting Program, please wait a second.."
    	sleep 2 && clear
    	exit 1

    fi
}

function main() {
	banner
	home
}
main